spring:
  application:
    name: product-service

  datasource:
    url: jdbc:postgresql://postgres:5432/product_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082

eureka:
  instance:
    hostname: product-service

  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/